image: nikolaik/python-nodejs

stages:
  - test

test:
  image: nikolaik/python-nodejs
  stage: test
  only:
    - merge_requests
  script:
    - yarn
    - yarn format
    - yarn typecheck
    - yarn lint
    - yarn build
