FROM node:14-alpine

ENV PORT 3000

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ARG NFT_ENDPOINT
ARG NEXT_PUBLIC_CHAIN_ID
ARG NEXT_PUBLIC_CHAIN_ENDPOINT
ARG NEXT_PUBLIC_BLOCK_EXPLORER
ENV NFT_ENDPOINT=$NFT_ENDPOINT
ENV NEXT_PUBLIC_CHAIN_ID=$NEXT_PUBLIC_CHAIN_ID
ENV NEXT_PUBLIC_CHAIN_ENDPOINT=$NEXT_PUBLIC_CHAIN_ENDPOINT
ENV NEXT_PUBLIC_BLOCK_EXPLORER=$NEXT_PUBLIC_BLOCK_EXPLORER
COPY package*.json /usr/src/app/
RUN yarn install

COPY . /usr/src/app

RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start" ]
